# Generated by Django 4.1.6 on 2023-02-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractCardOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeckModel",
            fields=[
                (
                    "abstractcardowner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cardgame.abstractcardowner",
                    ),
                ),
                ("deck_name", models.CharField(max_length=255)),
            ],
            bases=("cardgame.abstractcardowner",),
        ),
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "abstractcardowner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cardgame.abstractcardowner",
                    ),
                ),
                ("player_name", models.CharField(max_length=255)),
            ],
            bases=("cardgame.abstractcardowner",),
        ),
        migrations.CreateModel(
            name="CardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("CL", "Clubs"),
                            ("DI", "Diamonds"),
                            ("HE", "Hearts"),
                            ("SP", "Spades"),
                            ("", ""),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cardgame.abstractcardowner",
                    ),
                ),
            ],
        ),
    ]
