# Generated by Django 4.1.6 on 2023-02-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0005_alter_card_options_tablecardcollection_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="collection",
        ),
        migrations.AddField(
            model_name="card",
            name="collections",
            field=models.ManyToManyField(default=None, to="cardgame.cardcollection"),
        ),
    ]
