# Generated by Django 4.1.6 on 2023-02-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0006_remove_card_collection_card_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardcollection",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="card",
            name="collections",
            field=models.ManyToManyField(
                blank=True, default=None, to="cardgame.cardcollection"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="suit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Clubs"),
                    ("D", "Diamonds"),
                    ("H", "Hearts"),
                    ("S", "Spades"),
                    ("", ""),
                ],
                default="",
                max_length=1,
            ),
        ),
    ]
