# Generated by Django 4.1.6 on 2023-02-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0008_remove_playercardcollection_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={},
        ),
        migrations.RemoveField(
            model_name="card",
            name="collections",
        ),
        migrations.AddField(
            model_name="cardcollection",
            name="cards",
            field=models.ManyToManyField(blank=True, default=None, to="cardgame.card"),
        ),
    ]
