# Generated by Django 4.1.6 on 2023-02-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0003_alter_card_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="round_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
