# Generated by Django 4.1.6 on 2023-02-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0004_alter_game_round_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["number", "suit"]},
        ),
        migrations.AddField(
            model_name="tablecardcollection",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
