# Generated by Django 4.1.6 on 2023-02-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardgame", "0007_cardcollection_name_alter_card_collections_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playercardcollection",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tablecardcollection",
            name="name",
        ),
        migrations.AlterField(
            model_name="cardcollection",
            name="name",
            field=models.CharField(default="New Collection", max_length=255),
        ),
    ]
